Simple classification

In [2]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

study = np.array([[0],[0],[1],[1],[1],[0]])
result = np.array([0,1,0,1,1,0])

model = BernoulliNB()
model.fit(study, result)

new_data = np.array([[1]])
prediction = model.predict(new_data)
prediction_prob = model.predict_proba(new_data)

In [3]:
prediction

array([1])

In [4]:
prediction_prob

array([[0.4, 0.6]])

In [5]:
np.exp(model.class_log_prior_)

array([0.5, 0.5])

In [6]:
np.exp(model.feature_log_prob_)

array([[0.4],
       [0.6]])