Simple classification

In [2]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

study = np.array([[0],[0],[1],[1],[1],[0]])
result = np.array([0,1,0,1,1,0])

model = BernoulliNB()
model.fit(study, result)

new_data = np.array([[1]])
prediction = model.predict(new_data)
prediction_prob = model.predict_proba(new_data)

In [3]:
prediction

array([1])

In [4]:
prediction_prob

array([[0.4, 0.6]])

In [5]:
np.exp(model.class_log_prior_)

array([0.5, 0.5])

In [6]:
np.exp(model.feature_log_prob_)

array([[0.4],
       [0.6]])

Gaussian Naive Bayes Classifier

In [18]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

import pandas as pd
import math

In [10]:
#1D
iris = pd.read_csv('iris_1D.csv')
print(iris)

   Petal_Length  Label
0           1.4    0.0
1           1.0    0.0
2           1.3    0.0
3           1.9    0.0
4           2.0    0.0
5           3.8    1.0
6           4.1    1.0
7           3.9    1.0
8           4.2    1.0
9           3.4    1.0


In [11]:
X_train = iris.iloc[:, :-1].values
y_train = iris.iloc[:,-1].values

In [14]:
X_train

array([[1.4],
       [1. ],
       [1.3],
       [1.9],
       [2. ],
       [3.8],
       [4.1],
       [3.9],
       [4.2],
       [3.4]])

In [15]:
y_train

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [19]:
classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [20]:
x_test = np.array([[3.0]])
clf.predict_proba(x_test)

array([[0.0454125, 0.9545875]])

In [21]:
clf.class_count_

array([5., 5.])

In [22]:
clf.class_prior_

array([0.5, 0.5])

In [23]:
clf.classes_

array([0., 1.])

In [24]:
clf.var_

array([[0.1416],
       [0.0776]])

In [25]:
clf.theta_

array([[1.52],
       [3.88]])

In [28]:
#compute manually
def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var))*np.exp(-(data-mean)**2/(2*var))

In [39]:
data_c0 = iris.loc[iris.iloc[:,1] == 0, iris.columns[[0]]].to_numpy()
mean_c0 = data_c0.mean()
var_c0 = data_c0.var()

In [40]:
data_c1 = iris.loc[iris.iloc[:,1] == 1, iris.columns[[0]]].to_numpy()
mean_c1 = data_c1.mean()
var_c1 = data_c1.var()

In [41]:
x_test = np.array([[3.0]])
pdf_c0_x = gaussian_function(x_test, mean_c0, var_c0)
pdf_c1_x = gaussian_function(x_test, mean_c1, var_c1)

total = pdf_c0_x*0.5 + pdf_c1_x*0.5

pdf_c0_x = pdf_c0_x*0.5/total
pdf_c1_x = pdf_c1_x*0.5/total
print(pdf_c0_x)
print(pdf_c1_x)

[[0.0454125]]
[[0.9545875]]


In [42]:
#2D
iris = pd.read_csv('iris_2D.csv')
iris

Sepal_Length  Sepal_Width  Label
0            4.9          3.0      0
1            4.7          3.2      0
2            4.6          3.1      0
3            5.0          3.6      0
4            5.4          3.9      0
5            4.6          3.4      0
6            6.4          3.2      1
7            6.9          3.1      1
8            5.5          2.3      1
9            6.5          2.8      1
10           5.7          2.8      1
11           6.3          3.3      1

In [43]:
X_train = iris.iloc[:,:-1].values
y_train = iris.iloc[:,-1].values

In [45]:
classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [49]:
x_test = np.array([[4.1,2.9]])
clf.predict_proba(x_test)

array([[0.996191, 0.003809]])

In [50]:
clf.class_count_

array([6., 6.])

In [51]:
clf.var_

array([[0.07888889, 0.09555556],
       [0.22805556, 0.11138889]])

In [52]:
clf.class_prior_

array([0.5, 0.5])

In [54]:
clf.theta_

array([[4.86666667, 3.36666667],
       [6.21666667, 2.91666667]])

In [55]:
#compute manually 
gaussian_function(np.array([[4.1]]), 6.21666667, 0.22805556)

array([[4.52805727e-05]])

In [56]:
gaussian_function(np.array([[2.9]]), 2.91666667, 0.11138889)

array([[1.19384409]])

In [57]:
0.01412*0.5+0.000047*0.5

0.0070835

In [ ]:
# compute manually

data_c0 = np.array([4.9, 4.7, 4.6, 5. , 5.4, 4.6])
mean_c0 = data_c0.mean()
var_c0  = data_c0.var()
print(mean_c0)
print(var_c0)      

prob_c0 = gaussian_function(data_c0, mean_c0, var_c0)
print(prob_c0)

4.866666666666667
0.07888888888888902
[1.41040466 1.19108252 0.90503169 1.26901734 0.2341255  0.90503169]


In [60]:
data_c1 = np.array([3.8, 4.1, 3.9, 4.2, 3.4])
mean_c1 = data_c1.mean()
var_c1  = data_c1.var()
print(mean_c1)
print(var_c1)

prob_c1 = gaussian_function(data_c1, mean_c1, var_c1)
print(prob_c1)

3.88
0.07760000000000002
[1.37426395 1.0484362  1.42843305 0.74034542 0.3245289 ]


In [61]:
# predict manually

x_test = np.array([[3.0]])
dpf_c0_x = gaussian_function(x_test, mean_c0, var_c0)
dpf_c1_x = gaussian_function(x_test, mean_c1, var_c1)
print(dpf_c0_x)
print(dpf_c1_x)

# normalize
total = dpf_c0_x*0.5 + dpf_c1_x*0.5
print(total)
dpf_c0_x = dpf_c0_x*0.5/total
dpf_c1_x = dpf_c1_x*0.5/total

# print
print(dpf_c0_x)
print(dpf_c1_x)

[[3.64101612e-10]]
[[0.00974954]]
[[0.00487477]]
[[3.73455214e-08]]
[[0.99999996]]


In [62]:
#2D,3C
iris = pd.read_csv('iris_2D_3C.csv')

# Seperating the data into dependent and independent variables
X_train = iris.iloc[:, :-1].values
y_train = iris.iloc[:, -1].values

In [63]:
classifier = GaussianNB()
clf = classifier.fit(X_train, y_train)

In [64]:
# predict
x_test = np.array([[5.2, 2.4]])
clf.predict_proba(x_test)

array([[0.0418694 , 0.19180669, 0.76632391]])

In [65]:
clf.class_prior_

array([0.33333333, 0.33333333, 0.33333333])

In [66]:
clf.var_

array([[0.07888889, 0.09555556],
       [0.22805556, 0.11138889],
       [0.06888889, 0.08472222]])

In [67]:
clf.theta_

array([[4.86666667, 3.36666667],
       [6.21666667, 2.91666667],
       [5.53333333, 1.81666667]])